### ISSUE TITLE
Improve SVG export mini-project

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#1037]
Exporting to SVG is an important capability for generating resolution independent text on top of images and line plots. However, it is difficult to control the font size. As a first step, we want to simplify the SVG export dialog and behavior.

```[tasklist]
### Tasks
- [ ] https://github.com/nion-software/nionswift/issues/1051
- [ ] https://github.com/nion-software/nionswift/pull/1060
- [x] Allow height to be specified in inches, centimeters, or pixels
- [ ] https://github.com/nion-software/nionswift/issues/1124
- [ ] https://github.com/nion-software/nionswift/issues/1125
- [ ] https://github.com/nion-software/nionswift/issues/1126
- [ ] https://github.com/nion-software/nionswift/issues/1127
- [ ] Decide whether preserveAspectRatio needs to be set in the SVG file
- [ ] Allow multiple SVG items to be exported at once
- [ ] https://github.com/nion-software/nionswift/issues/1128
```

**Comment by cmeyer** [comment]
I merged the initial work by @lisham2000. I think we should add a resolution (ppi) when exporting to inches or cm (#1051).

I also added the following to the to-do list:

- Use min size of 3" and max of 12" (or equivalent in cm) for initial values
- Remember choice of inches/cm/pixels.

**Comment by jamesrussell216** [comment]
Hi @cmeyer, not urgent but I talked to @lisham2000 this morning and he said we were happy with where with this now pending potential further work in the future - is this issue OK to close now?

**Comment by cmeyer** [comment]
Sure I can close this with the additional note that #1126 is still open and desired, but not urgent.
