### ISSUE TITLE
Writing data files should occur in a thread

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#1066]
In order to avoid hanging the user interface when writing large data, writing to disk should be performed in a thread.

In the code today, writing occurs via the `Persistence.py` `write_external_data` method, which then calls `FileStorageSystem.py` `write_external_data` which then calls  `FileStorageSystem.py` `update_data`.

At one of these points, the write could put the write in a queue that is serviced by a thread.

The thread should handle data access while the write is pending.

The thread should also handle writing during shutdown (should probably complete the write).

Multiple threads could run simultaneously to write the data.

### Tasks
- [ ] Create thread to service writing requests
- [ ] Handle overlapping data and metadata writing requests
- [ ] Handle overlapping reading and writing requests
- [ ] Handle shutdown occurring during writing (finish writing)
