### ISSUE TITLE
Don't trigger long-computations recompute until user finishes editing parameters

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#1084]
The user should be able to edit all parameters and then trigger the computation with something like an Ok/Cancel button.

This probably implies that we need to classify computations into real-time or long-running.

There will also be combination situations where a real-time computation (Gaussian) is applied to a sequence/collection, making it into a long-running computation. In this case, it would be helpful to show the real-time computation applied to the element data (the displayed index in the sequence/collection).

### Tasks
- [x] https://github.com/nion-software/nionswift/issues/304
- [x] Allow computations to specify whether they are real-time or long-running.
- [x] Allow partial-real-time display of real-time computations applied to sequences/collections.
