### ISSUE TITLE
Computations should have way to set/remember default parameters

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#1085]
We have a few UI options:
- save and use the last used;
- add a button to the computation edit: "use these parameters as default"
- save/load named parameter sets

We might choose to have different options for different computations.

### Tasks
- [ ] Decide on UI
- [ ] Decide on persistent storage mechanism - also: stored per user or per project?
- [ ] Decide on persistent storage implementation
- [ ] Decide how much control to give to computations vs. general behavior
