### ISSUE TITLE
Allow flagging/tagging/rating and filtering of library items.

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#141]
Makes it easier for users to organize useful data.
```[tasklist]
### Tasks
- [ ] Propose a UI to enable/disable flags, tags, ratings
- [ ] Propose a UI of where to show flags, tags, ratings
- [ ] Propose a UI of how to filter for flags, tags, ratings
- [ ] Decide if flags, tags, ratings should be exported/imported - this helps decide where to store it
- [ ] Propose where to store the flags, tags, ratings based on decision above
- [ ] ... more items after design phase
```

**Comment by cmeyer** [comment]
Allow user to specify flagged (z), rejected (x), stars (0-5).

Allow user to filter by flagged, rejected, stars, data type, camera, metadata, etc.

**Comment by tcpekin** [comment]
Having generalizable, user-defined labels would be helpful (like these github label/hashtags), and then having automatic filtering/grouping of labels in the data panel per project would make sense.
