### ISSUE TITLE
Add zoom tool, zoom menu items

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#21]
- Select zoom tool with hot key
- Zoom should occur around mouse click or mouse location when appropriate
- Zoom menu items (in the View menu)

From Tracy:
For zooming in an out, we use "+", but then you are always zooming about the center. If we use the track wheel on the mouse, we could zoom about the cursor, and then you could zoom in on a particular feature.

From Niklas:
The best tracking devices, track balls often come without a scroll wheel, so making + and - move around the cursor would be better. There is a usability issue in Swift in that it doesn't actually know where the cursor is, but it should.

```[tasklist]
### Tasks
- [ ] https://github.com/nion-software/nionswift/issues/1137
- [ ] Add zoom menu items (zoom around mouse if cursor in panel, otherwise center)
- [ ] Add zoom by scroll wheel / track pad (zoom around mouse position)
```

**Comment by Brow71189** [comment]
Maybe both ideas should be implemented? But I definitely think Tracy's idea should, because this is what the mouse wheel does in most applications. Right now it moves images up/down in Swift, which is not very useful.
A nice side effect of zooming around the cursor is that you can use that to move the image around. Moving images is often a bit awkward in many programs, so using "zoom around the cursor" is a decent workaround.

Niklas' idea might be useful, too, but I 'm afraid that this can be confusing for users. Maybe we should just get trackballs with mouse wheels?

**Comment by ndellby** [comment]
I've looked, none of the good index finger trackballs come with scroll 
wheels, they only have the little minibuttons.

Niklas

**Comment by Brow71189** [comment]
When I looked I found a couple. For example
https://www.amazon.com/dp/B01936N73I/ref=cm_sw_r_cp_apa_i_pT83EbD923DSJ

Or

https://www.amazon.com/dp/B002OOWB3O/ref=cm_sw_r_cp_apa_i_UU83EbK0H5M6V

Or

https://www.amazon.com/dp/B0050SPZMK/ref=cm_sw_r_cp_apa_i_HV83EbKDZC718

Or

https://www.amazon.com/dp/B07J3XZYGG/ref=cm_sw_r_cp_apa_i_.W83EbJTYQY61

Or

https://www.amazon.com/dp/B0735584RM/ref=cm_sw_r_cp_apa_i_IY83Eb66VPXCW

Actually I think having a scroll wheel would be nice also for general use
of the user pc.


ndellby <notifications@github.com> schrieb am Di., 9. Juni 2020, 19:16:

**Comment by jamesrussell216** [comment]
PR for this currently is: https://github.com/nion-software/nionswift/pull/1073

**Comment by jamesrussell216** [comment]
After discussion on this issue we've got a proposed revised spec that @Tiomat85 is going to code too...

- One toolbar button for the zoom tool.
- Left-click to zoom in, modifier-left-click to zoom out, zooming around the mouse cursor position.
- Keep the +/- functionality; that should zoom around the centre of the image
- Leave the scroll wheel zooming functionality for now.
- Leave the left-click and drag to zooming functionality for now.

**Comment by Ion-e** [comment]
Implemented correctly, Thanks!
