### ISSUE TITLE
Add additional calibration options (even more than the other issue)

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#230]
Back to multiple kinds of displays, when I am setting up an experiment electrons per eV per s, makes sense, as my acquisition setup specifies eV per channel and seconds of acquisition. But when I am analyzing, then what I care about is how many electrons are in this bin, and what is the shot noise, if I have 1000 e in one eV with 10meV bins that means I expect 10% shot noise in each bin. So sensibly when I am analyzing I want e/eV. Software can't guess what I am doing and so it should just have different calibration options available.

ND 2019-02-21

See #154 
```[tasklist]
### Tasks
- [ ] https://github.com/nion-software/nionswift/issues/1007
- [x] Add dimensional calibration support for changing display calibrations
- [x] Add separate calibration styles for each set of calibrations (data, collection, sequence)
- [x] Add ability to change displayed intensity calibrations
- [x] Add a plug-in mechanism to provide intrinsic/calculated spatial/angular/temporal calibrations
- [ ] Add a way to switch the primary calibration to the displayed calibrations style (i.e. rad -> nm)
- [ ] Add ability to switch primary intensity calibration to displayed calibrations
- [ ] Consider adding a mechanism to revert to acquired-data original calibrations if they get switched
- [ ] https://github.com/nion-software/nionswift/issues/1017
```
