### ISSUE TITLE
Task list for Swift 0.15

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#318]
# Obsolete (change of plans or tracked separately)

- [X] Import folder should optionally create new project.
- [X] Maintain index on all relationships.
- [X] Make data items, computations, data structures visible in data panel.
- [X] #328 HDF5 project container
- [X] #460 Understand why adding 1000 data items via script takes so long.
- [X] Lines between panels do not draw making it difficult to see empty panels next to each other.
- [X] #368 Drag and drop items/dependencies between projects.
- [X] Also select items and context menu to move to another project
- [X] #118 Split items into new library (select items, then menu command)
- [X] #369 Documentation
- [X] Handle case of dragging into display panels when no work project is present (resolve item specifier after importing old project).
- [X] Unchecking old projects (not upgraded) may not be possible.
- [X] Project and collection selection should be persistent.
- [X] Migrating project file should remove profile fields, but only if latest version.
- [X] Better error message when work project can't be changed.
- [X] Changing work project should move or unlink live items so they get recreated.
- [X] Add ability to mount/unmount projects.
- [X] Make project unmount persistent.
- [X] Importing new projects adds one for each version. Either make this apparent or disable.

# Done

- [X] `test_deleting_processed_data_item_during_acquisition_recovers_correctly` intermittent
- [X] Switching workspaces with acquisition crash (could not reproduce).
- [x] Add configuration button to open project manager
- [x] Add options to display all projects (loaded and unloaded) in project panel.
- [X] Importing an existing project should only enable it, not create another.
- [X] Simplify project panel; introduce project manager window.
- [x] Change all uses of `receive_files` to specify project.
- [x] Handle data migration in future versions, i.e. check compatibility.
- [x] Debug missing data items and display item slice index validation.
- [x] Newly opened project is highlighted but not actually selected in project panel
- [x] Remove project sometimes fails
- [x] Allow user to set target/default project when snapping.
- [x] Consider moving source_uuid out of DataItem. Track relationships separately?
- [x] Think through read-only projects.
- [x] Cross correlate and other two input computations are broken
- [x] Deleting items is slow when many projects are present.
- [x] Handle duplicate projects (ignore?).
- [x] Write script to produce large projects; test performance.
- [x] Consolidate target_project_for_item and get_project_for_item calls.
- [x] Removing data structures probably fails
- [x] Check/uncheck entire folders in project panel
- [x] Clicking on project folder raises exception
- [x] Show full project/path in tool tip
- [x] Right click on project to show file location

# Additional Features

- [X] Handle Library 13 migration in same directory.  *deferred* until requested.
- [X] HDF5 based project (requires h5py 2.11) #328
- [X] Implement filters panel. #329
- [X] Consolidate/export project to directory/file. *deferred* until requested.
- [X] Add a duplicate project command. *deferred* until requested.
- [X] Load projects on a background thread (maybe necessary for performance) #330

# Future

- [X] Allow user to re-order files in project panel? Or alphabetize? #331
- [X] Create sample images package. #319
- [X] Browse mode which quickly shifts entire workspace to a browser style display, easy to switch back (needs more thought)

**Comment by cmeyer** [comment]
Closing this item. All bugs are tracked elsewhere.
