### ISSUE TITLE
Provide ability to select multiple graphics by dragging rubber band

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#58]
### Tasks
- [ ] Implement a tool in the raster display
- [ ] Add drawing code to show the rubber band while dragging
- [ ] Add tests for various functionality
- [ ] Dragging with shift key should select additional items

**Comment by Ion-e** [comment]
What is the requirement we are trying to solve by this feature? @cmeyer
