### ISSUE TITLE
Export batch with no boxes checked overwrites same file repeatedly

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#586]
When the user is exporting a set of files by selecting multiple display items and then choosing File > Export, the user is presented with a dialog that allows them to set the file naming template.

<img width="313" alt="image" src="https://github.com/nion-software/nionswift/assets/34664/43e0faa2-4c13-4cee-8c6c-aed9941eb571">

If they deselect all items, or if the combination of check boxes results in duplicate filenames, the export procedure simply overwrites the earlier export with the same filename.
```[tasklist]
### Tasks
- [ ] Rewrite `do_export` in `ExportDialog.py` to its own function external to the `ExportDialog` class
- [ ] In `do_export`, generate a map of display items to filenames, ensuring a unique filename for each display item
- [ ] Extra credit: Rewrite `ExportDialog` to use declarative (see how `ExportSVGHandler` does it)
- [ ] Extra credit: Move the functionality of `do_export` to a `Action` in `DocumentController.py` for scriptability, testing
```

**Comment by cmeyer** [comment]
XY reports "If I export multiple data with the same name (e.g. NionCCD-1010), only one file can be saved. I can check "Include Sequence Number" to allow them all to be saved. However, could you make this batch export smarter to automatically add sequence numbers if several items use the same file name."

**Comment by cmeyer** [comment]
The UI for the batch export resides in [`ExportDialog.py`](https://github.com/nion-software/nionswift/blob/master/nion/swift/ExportDialog.py).

Once the user has configured the options, the [`do_export`](https://github.com/nion-software/nionswift/blob/34bc02b87347cb0f939a546f9d42679ae2c549bd/nion/swift/ExportDialog.py#L159) method loops through the selected display items and exports them to a file using [write_display_item_with_writer](https://github.com/nion-software/nionswift/blob/34bc02b87347cb0f939a546f9d42679ae2c549bd/nion/swift/ExportDialog.py#L185).

**Comment by cmeyer** [comment]
Fixed 907bf563f6798a01d31c5848861dbded08428c9d

**Comment by Ion-e** [comment]
Issue verified as working correctly.

Thanks!
