### ISSUE TITLE
Move dependency storage into project (no source_uuid in DataItem).

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#778]
This is required to have more flexibility in managing dependencies between items.

See personal notes 2022-12-26 and 2022-12-27.

Note: for elemental mapping, sources are used for cascade delete; but also for identification of the data items in elemental mapping. Is there another way for identification? Parent is also used for a connection (needs more investigation).

EDIT: #1264 may be a better solution. Do that first.

### Tasks
- [ ] https://github.com/nion-software/nionswift/issues/1264
- [ ] Consider whether a garbage collection style dependency system would work better
- [ ] Consider whether allowing external objects to explicitly determine their dependencies via code would work better
