### ISSUE TITLE
Add an activity stream and associated UI

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#977]
This would record things like:

- useful for debugging
- useful as a log for returning to or reviewing a session

```[tasklist]
### Tasks
- [ ] https://github.com/nion-software/nionswift/issues/1009
- [ ] https://github.com/nion-software/nionswift-instrumentation-kit/issues/141
- [ ] projects opened/closed/created
- [ ] view modes started and stopped
- [ ] acquisitions performed
- [ ] run scripts
```
