### ISSUE TITLE
Make the inspector more useful

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#991]
Note: this is an umbrella issue. The effort for this issue is listed as "a day" since the work is done in sub-issues.

Also, this is listing the minimal viable product. I list other related issues for further improvement that are not direct tasks for the minimal viable product.

```[tasklist]
### Tasks
- [ ] #1028
- [ ] https://github.com/nion-software/nionswift/issues/1093
- [ ] Eliminate inspector computation section (available elsewhere)
- [ ] Eliminate redundant inspector Info section and add button in inspector to open title edit dialog
- [ ] https://github.com/nion-software/nionswift/issues/1081
- [ ] Make calibrations read-only if computed
- [ ] Allow calibrations to be specified even if computed
- [ ] Make it easier to change display style for dimensional and intensity calibrations
- [ ] Expose key metadata directly (exposure time, dispersion, etc.) (nion-instrumentation#37)
- [ ] https://github.com/nion-software/nion-instrumentation/issues/37
- [ ] #206
- [x] ~~Eliminate session inspector (available elsewhere)~~ Decided to keep until after acquisition object work
- [x] Ensure scroll wheel doesn't accidentally scroll combo boxes
```

### See Also (delayed, under consideration, or related)

- #1000
- #646
- #833
- #574
- #300
- #281
- #253
- #220
- #66

**Comment by jamesrussell216** [comment]
did you get a chance to update this one yesterday @cmeyer ?

**Comment by cmeyer** [comment]
> did you get a chance to update this one yesterday @cmeyer ?

Done

**Comment by cmeyer** [comment]
Sure I added it - but I would recommend against working on that issue right now - there are a ton of complexities with design and file format.

**Comment by jamesrussell216** [comment]
@cmeyer I made https://github.com/nion-software/nion-internal/issues/152 to cover that item in the task list just so I could define the spec of it in a little more detail (than just a task).
